### ISSUE TITLE
Updating backplane-cli to v0.1.10 wiped out all of its and ocm's configuration files

### ISSUE THREAD

**Issue by erdii** [openshift/backplane-cli#187]
Since I've upgraded to `v0.1.10`, all my backplane and ocm config files where completely wiped out.
This has also happened to a colleague of mine: @pat-cremin

I don't know how it happened, I have skimmed through this repo's source code as well and couldn't find anything (other than maybe somehow accidentally setting `KUBECONFIG` to config file path and then triggering backplane-cli's kubeconfig cleanup by, eg logging out of a cluster - which I **definitely** haven't done!). I have also skimmed through [openshift-online/ocm-cli](https://github.com/openshift-online/ocm-cli/) but couldn't find any suspicious code either.

I don't know if this will lead anywhere but I'll dump my brain in here, really hoping to find the root-cause.

## Installation methods used

- My machine (Linux/Arch): I've used this [AUR package](https://aur.archlinux.org/packages/backplane-cli) which basically [builds backplane-cli](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=backplane-cli) using `goreleaser build --clean --single-target -o .`.
- @pat-cremin's machine (Linux/Fedora): He has used `go install ...` to install.

## My setup

I had the config files set up like this:
```
.config
├── backplane
│   ├── config.prod.json
│   └── config.stage.json
└── ocm
    ├── config.prod.json
    └── config.stage.json
```

and configured ocm-cli+backplane-cli  when I needed them with:

```
export OCM_CONFIG="$HOME/.config/ocm/config.prod.json"
export BACKPLANE_CONFIG="$HOME/.config/backplane/config.prod.json"
```
or
```
export OCM_CONFIG="$HOME/.config/ocm/config.stage.json"
export BACKPLANE_CONFIG="$HOME/.config/backplane/config.stage.json"
```

I'm *pretty sure* that I haven't productively used backplane-cli after the upgrade but both ocm and backplane config files are gone. The folders are now empty.

**Comment by bmeng** [comment]
@erdii As we discussed on slack, we should use `ocm backplane upgrade` instead of `go install ...` for backplane upgrade. Do you still think this is an issue?
